steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/primal-graph-374308/trainer_timm_ln:latest', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/primal-graph-374308/trainer_timm_ln:latest']
