# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/primal-graph-374308/trainer_timm_ln:latest
      env:
        - name: WANDB_API_KEY
          value: WANDB_API_KEY_SECRET
