name: Docker Image CI

on:
  push:
    branches: [ main, 4-setup-unit-testing ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker build . --file Dockerfile --tag tester:$(date +%s)
        docker push tester:$(date +%s)
