name: "Run unit tests"

on:
  push:
    branches: [ master, main, dvc_unittest ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: unit-tests
    runs-on: ${{ matrix.os }}

    strategy:
            matrix:
                os: [ubuntu-latest] # , macos-latest, windows-latest
                node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Pull data from DVC
      run: |
        dvc pull
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
